// challenges/challenge-samples/svelte-example-challenge/solutionFiles/ImageSlider.svelte
<script>
  export let images = [];

  let currentImage = 0;

  $: isPrevDisabled = currentImage === 0;
  $: isNextDisabled = currentImage === images.length - 1;

  function nextImage() {
    if (currentImage !== images.length - 1) {
      currentImage++;
    }
  }

  function previousImage() {
    if (currentImage !== 0) {
      currentImage--;
    }
  }
</script>

<div>
  <img
    src={images[currentImage]}
    width="200"
    height="250"
    alt="Image {currentImage + 1}" />
  <button disabled={isPrevDisabled} on:click={previousImage}> Previous </button>
  <button disabled={isNextDisabled} on:click={nextImage}> Next </button>
</div>

// challenges/challenge-samples/reactts-example-challenge/solutionFiles/ImageSlider.tsx
import React, { useState } from "react";

interface ImageSliderProps {
  images?: string[];
}

const ImageSlider: React.FC<ImageSliderProps> = ({ images = [] }) => {
  const [currentImage, setCurrentImage] = useState<number>(0);

  const isPrevDisabled = currentImage === 0;
  const isNextDisabled = currentImage === images.length - 1;

  const nextImage = () => {
    if (!isNextDisabled) setCurrentImage(currentImage + 1);
  };

  const previousImage = () => {
    if (!isPrevDisabled) setCurrentImage(currentImage - 1);
  };

  return (
    <div className="text-center">
      {images.length > 0 && (
        <img
          src={images[currentImage]}
          alt={`Slide ${currentImage + 1}`}
          width={400}
          height={500}
        />
      )}

      <div className="mt-2">
        <button onClick={previousImage} disabled={isPrevDisabled}>
          Previous
        </button>
        <button onClick={nextImage} disabled={isNextDisabled}>
          Next
        </button>
      </div>
    </div>
  );
};

export default ImageSlider;
