// challenges/challenge-samples/reactts-example-challenge/solutionFiles/ImageSlider.tsx
import React, { useState } from "react";

interface ImageSliderProps {
  images?: string[];
}

const ImageSlider: React.FC<ImageSliderProps> = ({ images = [] }) => {
  const [currentImage, setCurrentImage] = useState<number>(0);

  const isPrevDisabled = currentImage === 0;
  const isNextDisabled = currentImage === images.length - 1;

  const nextImage = () => {
    if (!isNextDisabled) setCurrentImage(currentImage + 1);
  };

  const previousImage = () => {
    if (!isPrevDisabled) setCurrentImage(currentImage - 1);
  };

  return (
    <div className="text-center">
      {images.length > 0 && (
        <img
          src={images[currentImage]}
          alt={`Slide ${currentImage + 1}`}
          width={400}
          height={500}
        />
      )}

      <div className="mt-2">
        <button onClick={previousImage} disabled={isPrevDisabled}>
          Previous
        </button>
        <button onClick={nextImage} disabled={isNextDisabled}>
          Next
        </button>
      </div>
    </div>
  );
};

export default ImageSlider;

// challenges/challenge-samples/vuejs-example-challenge/solutionFiles/ImageSlider.vue
<template>
  <div class="text-center">
    <img :src="images[currentImage]" width="400" height="500" />
    <button
      class="btn btn-primary"
      :disabled="isPrevDisabled"
      @click="previousImage"
    >
      Previous
    </button>
    <button
      class="btn btn-primary"
      :disabled="isNextDisabled"
      @click="nextImage"
    >
      Next
    </button>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

const props = defineProps({
  images: {
    type: Array,
    default: [],
  },
});

const currentImage = ref(0);

const isPrevDisabled = computed(() => {
  return currentImage.value === 0;
});

const isNextDisabled = computed(() => {
  return currentImage.value === props.images.length - 1;
});

const nextImage = function (e) {
  if (currentImage.value !== props.images.length - 1) currentImage.value++;
};

const previousImage = function (e) {
  if (currentImage.value !== 0) currentImage.value--;
};
</script>

<style>
.removed {
  color: gray;
}

.removed label {
  text-decoration: line-through;
}
</style>
