// challenges/challenge-samples/solidjs_ts-write-the-tests-example-challenge/mutants/accepts-blank/App.tsx
import { createSignal, For } from 'solid-js';

export default function App() {
  const [items, setItems] = createSignal<string[]>([]);
  const [draft, setDraft] = createSignal('');

  const addTodo = (): void => {
    const text = draft().trim();

    if (items().some((item) => item.toLowerCase() === text.toLowerCase())) return;

    setItems([...items(), text]);
    setDraft('');
  };

  return (
    <div>
      <h1>Todos ({items().length})</h1>
      <input
        placeholder="What needs to be done?"
        value={draft()}
        onInput={(event) => setDraft(event.currentTarget.value)}
      />
      <button onClick={addTodo}>Add</button>
      <ul>
        <For each={items()}>{(item) => <li>{item}</li>}</For>
      </ul>
    </div>
  );
}

// challenges/challenge-samples/reactts-write-the-tests-example-challenge/solutionFiles/App.tsx
import React, { useState } from "react";

const App: React.FC = () => {
  const [items, setItems] = useState<string[]>([]);
  const [draft, setDraft] = useState("");

  const addTodo = (): void => {
    const text = draft.trim();

    if (text.length === 0) return;

    if (items.some((item) => item.toLowerCase() === text.toLowerCase())) return;

    setItems([...items, text]);
    setDraft("");
  };

  return (
    <div>
      <h1>Todos ({items.length})</h1>
      <input
        placeholder="What needs to be done?"
        value={draft}
        onChange={(event) => setDraft(event.target.value)}
      />
      <button onClick={addTodo}>Add</button>
      <ul>
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
};

export default App;
