// challenges/challenge-samples/angular-example-challenge/solutionFiles/ImageSlider.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "image-slider",
  templateUrl: "./ImageSlider.component.html",
})
export class ImageSliderComponent {
  @Input() images: string[] = [];

  currentImage = 0;

  get isPrevDisabled() {
    return this.currentImage === 0;
  }
  get isNextDisabled() {
    return (
      this.images.length === 0 || this.currentImage >= this.images.length - 1
    );
  }

  nextImage() {
    if (this.currentImage < this.images.length - 1) this.currentImage++;
  }
  previousImage() {
    if (this.currentImage > 0) this.currentImage--;
  }
}

<div>
  <img
    [src]="images[currentImage]"
    width="200"
    height="250"
    [alt]="'Image ' + (currentImage + 1)"
  />
  <button [disabled]="isPrevDisabled" (click)="previousImage()">
    Previous
  </button>
  <button [disabled]="isNextDisabled" (click)="nextImage()">Next</button>
</div>

// challenges/challenge-samples/reactjs-example-challenge/solutionFiles/ImageSlider.jsx
import React, { useState } from "react";

function ImageSlider({ images = [] }) {
  const [currentImage, setCurrentImage] = useState(0);

  const isPrevDisabled = currentImage === 0;
  const isNextDisabled = currentImage === images.length - 1;

  const nextImage = () => {
    if (currentImage !== images.length - 1) {
      setCurrentImage(currentImage + 1);
    }
  };

  const previousImage = () => {
    if (currentImage !== 0) {
      setCurrentImage(currentImage - 1);
    }
  };

  return (
    <div>
      <img
        src={images[currentImage]}
        width="200"
        height="250"
        alt={`Image ${currentImage + 1}`}
      />
      <button disabled={isPrevDisabled} onClick={previousImage}>
        Previous
      </button>
      <button disabled={isNextDisabled} onClick={nextImage}>
        Next
      </button>
    </div>
  );
}

export default ImageSlider;
